[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
subxt = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
